module.exports = {
    SINGLE_QUOTE: "'",
    DOUBLE_QUOTE: '"',
    COLON: ":",
    COMMA: ",",
    BRACKET_OPEN: "(",
    BRACKET_CLOSE: ")",
    CURLY_BRACKET_OPEN: "{",
    CURLY_BRACKET_CLOSE: "}",
    SQUARE_BRACKET_OPEN: "[",
    SQUARE_BRACKET_CLOSE: "]",
    PIPE: "|",
    ARROW: "=>",
    SPACER: " ",
    BACKSLASH: "\\",
    LINE_BREAK: "\n",
    TAB: "\t",
    PERCENT: "%",
    FOR_KEYWORD: "for",
    IN_KEYWORD: "in",
    ENDFOR_KEYWORD: "endfor",
    IF_KEYWORD: "if",
    ELSE_KEYWORD: "else",
    ELSEIF_KEYWORD: "elseif",
    ENDIF_KEYWORD: "endif",
    STYLE_KEYWORD: "style",
    DELIMITER_SIZE: 2, //This represent "{{", "}}", "{%", "%}"
    GENERIC_OPEN: "{%",
    GENERIC_CLOSE: "%}",
    STANDALONE_OPEN: "{{",
    STANDALONE_CLOSE: "}}",
};


